//
//  PlaidConfiguration.swift
//  LinkDemo-Swift
//
//  Created by Nathan Tindall on 6/17/20.
//  Copyright © 2020 Plaid Inc. All rights reserved.
//


struct PlaidConfiguration {
    #warning("Replace the example oauthRedirectUri below with your oauthRedirectUri, which should be configured as a universal link and must be configured through Plaid's developer dashboard")
    static let OAuthRedirectUri = "";
    #warning("Add the country codes that you want to enable access for")
    static let CountryCodes = ["US"];
    #warning("Configure your plaid public key here")
    static let PublicKey = "YOUR_PLAID_PUBLIC_KEY";
    #warning("Replace GENERATED_PUBLIC_TOKEN below with the public token you want to use -- note that this will need to be dynamically generated by your application.")
    static let GeneratedPublicToken = "GENERATED_PUBLIC_TOKEN";
    #warning("Replace GENERATED_ITEM_ADD_TOKEN below with your generated item add token -- this will also need to be dynamically generated by your application.")
    static let GeneratedItemAddToken = "GENERATED_ITEM_ADD_TOKEN";
}
